/*
 * Ported from nbvcxz (the adjacency graph tables of me.gosimple.nbvcxz.resources.AdjacencyGraphUtil).
 * Copyright (c) 2017, Adam Brusselback. MIT licence — see LICENSE-nbvcxz.txt.
 *
 * Converted mechanically from the Java source rather than retyped, so the tables are provably the
 * same data. Each entry maps a key to its neighbours, one slot per direction; a null slot means
 * there is no key that way. Every slot holds the unshifted and shifted character of that key, which
 * is how the shift count is recovered later.
 */
@file:Suppress("MaxLineLength")

package com.takaotech.password.resources

internal object KeyboardGraphs {

    private val QWERTY: Map<Char, Array<String?>> = mapOf(
        '0' to arrayOf("9(", null, null, "-_", "pP", "oO"),
        '1' to arrayOf("`~", null, null, "2@", "qQ", null),
        '2' to arrayOf("1!", null, null, "3#", "wW", "qQ"),
        '3' to arrayOf("2@", null, null, "4\$", "eE", "wW"),
        '4' to arrayOf("3#", null, null, "5%", "rR", "eE"),
        '5' to arrayOf("4\$", null, null, "6^", "tT", "rR"),
        '6' to arrayOf("5%", null, null, "7&", "yY", "tT"),
        '7' to arrayOf("6^", null, null, "8*", "uU", "yY"),
        '8' to arrayOf("7&", null, null, "9(", "iI", "uU"),
        '9' to arrayOf("8*", null, null, "0)", "oO", "iI"),
        '!' to arrayOf("`~", null, null, "2@", "qQ", null),
        '"' to arrayOf(";:", "[{", "]}", null, null, "/?"),
        '#' to arrayOf("2@", null, null, "4\$", "eE", "wW"),
        '$' to arrayOf("3#", null, null, "5%", "rR", "eE"),
        '%' to arrayOf("4\$", null, null, "6^", "tT", "rR"),
        '&' to arrayOf("6^", null, null, "8*", "uU", "yY"),
        '\'' to arrayOf(";:", "[{", "]}", null, null, "/?"),
        '(' to arrayOf("8*", null, null, "0)", "oO", "iI"),
        ')' to arrayOf("9(", null, null, "-_", "pP", "oO"),
        '*' to arrayOf("7&", null, null, "9(", "iI", "uU"),
        '+' to arrayOf("-_", null, null, null, "]}", "[{"),
        ',' to arrayOf("mM", "kK", "lL", ".>", null, null),
        '-' to arrayOf("0)", null, null, "=+", "[{", "pP"),
        '.' to arrayOf(",<", "lL", ";:", "/?", null, null),
        '/' to arrayOf(".>", ";:", "'\"", null, null, null),
        ':' to arrayOf("lL", "pP", "[{", "'\"", "/?", ".>"),
        ';' to arrayOf("lL", "pP", "[{", "'\"", "/?", ".>"),
        '<' to arrayOf("mM", "kK", "lL", ".>", null, null),
        '=' to arrayOf("-_", null, null, null, "]}", "[{"),
        '>' to arrayOf(",<", "lL", ";:", "/?", null, null),
        '?' to arrayOf(".>", ";:", "'\"", null, null, null),
        '@' to arrayOf("1!", null, null, "3#", "wW", "qQ"),
        'A' to arrayOf(null, "qQ", "wW", "sS", "zZ", null),
        'B' to arrayOf("vV", "gG", "hH", "nN", null, null),
        'C' to arrayOf("xX", "dD", "fF", "vV", null, null),
        'D' to arrayOf("sS", "eE", "rR", "fF", "cC", "xX"),
        'E' to arrayOf("wW", "3#", "4\$", "rR", "dD", "sS"),
        'F' to arrayOf("dD", "rR", "tT", "gG", "vV", "cC"),
        'G' to arrayOf("fF", "tT", "yY", "hH", "bB", "vV"),
        'H' to arrayOf("gG", "yY", "uU", "jJ", "nN", "bB"),
        'I' to arrayOf("uU", "8*", "9(", "oO", "kK", "jJ"),
        'J' to arrayOf("hH", "uU", "iI", "kK", "mM", "nN"),
        'K' to arrayOf("jJ", "iI", "oO", "lL", ",<", "mM"),
        'L' to arrayOf("kK", "oO", "pP", ";:", ".>", ",<"),
        'M' to arrayOf("nN", "jJ", "kK", ",<", null, null),
        'N' to arrayOf("bB", "hH", "jJ", "mM", null, null),
        'O' to arrayOf("iI", "9(", "0)", "pP", "lL", "kK"),
        'P' to arrayOf("oO", "0)", "-_", "[{", ";:", "lL"),
        'Q' to arrayOf(null, "1!", "2@", "wW", "aA", null),
        'R' to arrayOf("eE", "4\$", "5%", "tT", "fF", "dD"),
        'S' to arrayOf("aA", "wW", "eE", "dD", "xX", "zZ"),
        'T' to arrayOf("rR", "5%", "6^", "yY", "gG", "fF"),
        'U' to arrayOf("yY", "7&", "8*", "iI", "jJ", "hH"),
        'V' to arrayOf("cC", "fF", "gG", "bB", null, null),
        'W' to arrayOf("qQ", "2@", "3#", "eE", "sS", "aA"),
        'X' to arrayOf("zZ", "sS", "dD", "cC", null, null),
        'Y' to arrayOf("tT", "6^", "7&", "uU", "hH", "gG"),
        'Z' to arrayOf(null, "aA", "sS", "xX", null, null),
        '[' to arrayOf("pP", "-_", "=+", "]}", "'\"", ";:"),
        '\\' to arrayOf("]}", null, null, null, null, null),
        ']' to arrayOf("[{", "=+", null, "\\|", null, "'\""),
        '^' to arrayOf("5%", null, null, "7&", "yY", "tT"),
        '_' to arrayOf("0)", null, null, "=+", "[{", "pP"),
        '`' to arrayOf(null, null, null, "1!", null, null),
        'a' to arrayOf(null, "qQ", "wW", "sS", "zZ", null),
        'b' to arrayOf("vV", "gG", "hH", "nN", null, null),
        'c' to arrayOf("xX", "dD", "fF", "vV", null, null),
        'd' to arrayOf("sS", "eE", "rR", "fF", "cC", "xX"),
        'e' to arrayOf("wW", "3#", "4\$", "rR", "dD", "sS"),
        'f' to arrayOf("dD", "rR", "tT", "gG", "vV", "cC"),
        'g' to arrayOf("fF", "tT", "yY", "hH", "bB", "vV"),
        'h' to arrayOf("gG", "yY", "uU", "jJ", "nN", "bB"),
        'i' to arrayOf("uU", "8*", "9(", "oO", "kK", "jJ"),
        'j' to arrayOf("hH", "uU", "iI", "kK", "mM", "nN"),
        'k' to arrayOf("jJ", "iI", "oO", "lL", ",<", "mM"),
        'l' to arrayOf("kK", "oO", "pP", ";:", ".>", ",<"),
        'm' to arrayOf("nN", "jJ", "kK", ",<", null, null),
        'n' to arrayOf("bB", "hH", "jJ", "mM", null, null),
        'o' to arrayOf("iI", "9(", "0)", "pP", "lL", "kK"),
        'p' to arrayOf("oO", "0)", "-_", "[{", ";:", "lL"),
        'q' to arrayOf(null, "1!", "2@", "wW", "aA", null),
        'r' to arrayOf("eE", "4\$", "5%", "tT", "fF", "dD"),
        's' to arrayOf("aA", "wW", "eE", "dD", "xX", "zZ"),
        't' to arrayOf("rR", "5%", "6^", "yY", "gG", "fF"),
        'u' to arrayOf("yY", "7&", "8*", "iI", "jJ", "hH"),
        'v' to arrayOf("cC", "fF", "gG", "bB", null, null),
        'w' to arrayOf("qQ", "2@", "3#", "eE", "sS", "aA"),
        'x' to arrayOf("zZ", "sS", "dD", "cC", null, null),
        'y' to arrayOf("tT", "6^", "7&", "uU", "hH", "gG"),
        'z' to arrayOf(null, "aA", "sS", "xX", null, null),
        '{' to arrayOf("pP", "-_", "=+", "]}", "'\"", ";:"),
        '|' to arrayOf("]}", null, null, null, null, null),
        '}' to arrayOf("[{", "=+", null, "\\|", null, "'\""),
        '~' to arrayOf(null, null, null, "1!", null, null),
    )

    private val DVORAK: Map<Char, Array<String?>> = mapOf(
        '0' to arrayOf("9(", null, null, "[{", "lL", "rR"),
        '1' to arrayOf("`~", null, null, "2@", "'\"", null),
        '2' to arrayOf("1!", null, null, "3#", ",<", "'\""),
        '3' to arrayOf("2@", null, null, "4\$", ".>", ",<"),
        '4' to arrayOf("3#", null, null, "5%", "pP", ".>"),
        '5' to arrayOf("4\$", null, null, "6^", "yY", "pP"),
        '6' to arrayOf("5%", null, null, "7&", "fF", "yY"),
        '7' to arrayOf("6^", null, null, "8*", "gG", "fF"),
        '8' to arrayOf("7&", null, null, "9(", "cC", "gG"),
        '9' to arrayOf("8*", null, null, "0)", "rR", "cC"),
        '!' to arrayOf("`~", null, null, "2@", "'\"", null),
        '"' to arrayOf(null, "1!", "2@", ",<", "aA", null),
        '#' to arrayOf("2@", null, null, "4\$", ".>", ",<"),
        '$' to arrayOf("3#", null, null, "5%", "pP", ".>"),
        '%' to arrayOf("4\$", null, null, "6^", "yY", "pP"),
        '&' to arrayOf("6^", null, null, "8*", "gG", "fF"),
        '\'' to arrayOf(null, "1!", "2@", ",<", "aA", null),
        '(' to arrayOf("8*", null, null, "0)", "rR", "cC"),
        ')' to arrayOf("9(", null, null, "[{", "lL", "rR"),
        '*' to arrayOf("7&", null, null, "9(", "cC", "gG"),
        '+' to arrayOf("/?", "]}", null, "\\|", null, "-_"),
        ',' to arrayOf("'\"", "2@", "3#", ".>", "oO", "aA"),
        '-' to arrayOf("sS", "/?", "=+", null, null, "zZ"),
        '.' to arrayOf(",<", "3#", "4\$", "pP", "eE", "oO"),
        '/' to arrayOf("lL", "[{", "]}", "=+", "-_", "sS"),
        ':' to arrayOf(null, "aA", "oO", "qQ", null, null),
        ';' to arrayOf(null, "aA", "oO", "qQ", null, null),
        '<' to arrayOf("'\"", "2@", "3#", ".>", "oO", "aA"),
        '=' to arrayOf("/?", "]}", null, "\\|", null, "-_"),
        '>' to arrayOf(",<", "3#", "4\$", "pP", "eE", "oO"),
        '?' to arrayOf("lL", "[{", "]}", "=+", "-_", "sS"),
        '@' to arrayOf("1!", null, null, "3#", ",<", "'\""),
        'A' to arrayOf(null, "'\"", ",<", "oO", ";:", null),
        'B' to arrayOf("xX", "dD", "hH", "mM", null, null),
        'C' to arrayOf("gG", "8*", "9(", "rR", "tT", "hH"),
        'D' to arrayOf("iI", "fF", "gG", "hH", "bB", "xX"),
        'E' to arrayOf("oO", ".>", "pP", "uU", "jJ", "qQ"),
        'F' to arrayOf("yY", "6^", "7&", "gG", "dD", "iI"),
        'G' to arrayOf("fF", "7&", "8*", "cC", "hH", "dD"),
        'H' to arrayOf("dD", "gG", "cC", "tT", "mM", "bB"),
        'I' to arrayOf("uU", "yY", "fF", "dD", "xX", "kK"),
        'J' to arrayOf("qQ", "eE", "uU", "kK", null, null),
        'K' to arrayOf("jJ", "uU", "iI", "xX", null, null),
        'L' to arrayOf("rR", "0)", "[{", "/?", "sS", "nN"),
        'M' to arrayOf("bB", "hH", "tT", "wW", null, null),
        'N' to arrayOf("tT", "rR", "lL", "sS", "vV", "wW"),
        'O' to arrayOf("aA", ",<", ".>", "eE", "qQ", ";:"),
        'P' to arrayOf(".>", "4\$", "5%", "yY", "uU", "eE"),
        'Q' to arrayOf(";:", "oO", "eE", "jJ", null, null),
        'R' to arrayOf("cC", "9(", "0)", "lL", "nN", "tT"),
        'S' to arrayOf("nN", "lL", "/?", "-_", "zZ", "vV"),
        'T' to arrayOf("hH", "cC", "rR", "nN", "wW", "mM"),
        'U' to arrayOf("eE", "pP", "yY", "iI", "kK", "jJ"),
        'V' to arrayOf("wW", "nN", "sS", "zZ", null, null),
        'W' to arrayOf("mM", "tT", "nN", "vV", null, null),
        'X' to arrayOf("kK", "iI", "dD", "bB", null, null),
        'Y' to arrayOf("pP", "5%", "6^", "fF", "iI", "uU"),
        'Z' to arrayOf("vV", "sS", "-_", null, null, null),
        '[' to arrayOf("0)", null, null, "]}", "/?", "lL"),
        '\\' to arrayOf("=+", null, null, null, null, null),
        ']' to arrayOf("[{", null, null, null, "=+", "/?"),
        '^' to arrayOf("5%", null, null, "7&", "fF", "yY"),
        '_' to arrayOf("sS", "/?", "=+", null, null, "zZ"),
        '`' to arrayOf(null, null, null, "1!", null, null),
        'a' to arrayOf(null, "'\"", ",<", "oO", ";:", null),
        'b' to arrayOf("xX", "dD", "hH", "mM", null, null),
        'c' to arrayOf("gG", "8*", "9(", "rR", "tT", "hH"),
        'd' to arrayOf("iI", "fF", "gG", "hH", "bB", "xX"),
        'e' to arrayOf("oO", ".>", "pP", "uU", "jJ", "qQ"),
        'f' to arrayOf("yY", "6^", "7&", "gG", "dD", "iI"),
        'g' to arrayOf("fF", "7&", "8*", "cC", "hH", "dD"),
        'h' to arrayOf("dD", "gG", "cC", "tT", "mM", "bB"),
        'i' to arrayOf("uU", "yY", "fF", "dD", "xX", "kK"),
        'j' to arrayOf("qQ", "eE", "uU", "kK", null, null),
        'k' to arrayOf("jJ", "uU", "iI", "xX", null, null),
        'l' to arrayOf("rR", "0)", "[{", "/?", "sS", "nN"),
        'm' to arrayOf("bB", "hH", "tT", "wW", null, null),
        'n' to arrayOf("tT", "rR", "lL", "sS", "vV", "wW"),
        'o' to arrayOf("aA", ",<", ".>", "eE", "qQ", ";:"),
        'p' to arrayOf(".>", "4\$", "5%", "yY", "uU", "eE"),
        'q' to arrayOf(";:", "oO", "eE", "jJ", null, null),
        'r' to arrayOf("cC", "9(", "0)", "lL", "nN", "tT"),
        's' to arrayOf("nN", "lL", "/?", "-_", "zZ", "vV"),
        't' to arrayOf("hH", "cC", "rR", "nN", "wW", "mM"),
        'u' to arrayOf("eE", "pP", "yY", "iI", "kK", "jJ"),
        'v' to arrayOf("wW", "nN", "sS", "zZ", null, null),
        'w' to arrayOf("mM", "tT", "nN", "vV", null, null),
        'x' to arrayOf("kK", "iI", "dD", "bB", null, null),
        'y' to arrayOf("pP", "5%", "6^", "fF", "iI", "uU"),
        'z' to arrayOf("vV", "sS", "-_", null, null, null),
        '{' to arrayOf("0)", null, null, "]}", "/?", "lL"),
        '|' to arrayOf("=+", null, null, null, null, null),
        '}' to arrayOf("[{", null, null, null, "=+", "/?"),
        '~' to arrayOf(null, null, null, "1!", null, null),
    )

    private val STANDARD_KEYPAD: Map<Char, Array<String?>> = mapOf(
        '0' to arrayOf(null, "1", "2", "3", ".", null, null, null),
        '1' to arrayOf(null, null, "4", "5", "2", "0", null, null),
        '2' to arrayOf("1", "4", "5", "6", "3", ".", "0", null),
        '3' to arrayOf("2", "5", "6", null, null, null, ".", "0"),
        '4' to arrayOf(null, null, "7", "8", "5", "2", "1", null),
        '5' to arrayOf("4", "7", "8", "9", "6", "3", "2", "1"),
        '6' to arrayOf("5", "8", "9", "+", null, null, "3", "2"),
        '7' to arrayOf(null, null, null, "/", "8", "5", "4", null),
        '8' to arrayOf("7", null, "/", "*", "9", "6", "5", "4"),
        '9' to arrayOf("8", "/", "*", "-", "+", null, "6", "5"),
        '*' to arrayOf("/", null, null, null, "-", "+", "9", "8"),
        '+' to arrayOf("9", "*", "-", null, null, null, null, "6"),
        '-' to arrayOf("*", null, null, null, null, null, "+", "9"),
        '.' to arrayOf("0", "2", "3", null, null, null, null, null),
        '/' to arrayOf(null, null, null, null, "*", "9", "8", "7"),
    )

    private val MAC_KEYPAD: Map<Char, Array<String?>> = mapOf(
        '0' to arrayOf(null, "1", "2", "3", ".", null, null, null),
        '1' to arrayOf(null, null, "4", "5", "2", "0", null, null),
        '2' to arrayOf("1", "4", "5", "6", "3", ".", "0", null),
        '3' to arrayOf("2", "5", "6", "+", null, null, ".", "0"),
        '4' to arrayOf(null, null, "7", "8", "5", "2", "1", null),
        '5' to arrayOf("4", "7", "8", "9", "6", "3", "2", "1"),
        '6' to arrayOf("5", "8", "9", "-", "+", null, "3", "2"),
        '7' to arrayOf(null, null, null, "=", "8", "5", "4", null),
        '8' to arrayOf("7", null, "=", "/", "9", "6", "5", "4"),
        '9' to arrayOf("8", "=", "/", "*", "-", "+", "6", "5"),
        '*' to arrayOf("/", null, null, null, null, null, "-", "9"),
        '+' to arrayOf("6", "9", "-", null, null, null, null, "3"),
        '-' to arrayOf("9", "/", "*", null, null, null, "+", "6"),
        '.' to arrayOf("0", "2", "3", null, null, null, null, null),
        '/' to arrayOf("=", null, null, null, "*", "-", "9", "8"),
        '=' to arrayOf(null, null, null, null, "/", "9", "8", "7"),
    )

    /**
     * The graphs the spatial matcher walks by default — QWERTY plus the two keypads, matching
     * upstream. Dvorak is deliberately left out there and stays out here.
     */
    val defaults: List<AdjacencyGraph> = listOf(
        AdjacencyGraph("Qwerty", QWERTY),
        AdjacencyGraph("Standard Keypad", STANDARD_KEYPAD),
        AdjacencyGraph("Mac Keypad", MAC_KEYPAD),
    )

    /** Available for callers that want it, but not part of [defaults]. */
    val dvorak: AdjacencyGraph = AdjacencyGraph("Dvorak", DVORAK)
}
