package com.takaotech.ktravel.core.telemetry

import com.takaotech.ktravel.core.logging.LogLevel

/**
 * Where diagnostics go when they leave the device.
 *
 * An interface with two implementations chosen at build time: the Kotzilla one when a `kotzilla.json`
 * is present, and a no-op otherwise (see the source set switch in `composeApp/build.gradle.kts`).
 * That is what keeps a clone without the key — CI included — building and running exactly like the
 * real thing, minus the sending.
 */
interface TelemetrySink {

    /** Starts the backend. Called once per process, from the platform entry point. */
    fun start()

    /**
     * Tells the backend what the user decided.
     *
     * @param consent The decision, including [TelemetryConsent.Unknown] when it has expired.
     */
    fun applyConsent(consent: TelemetryConsent)

    /**
     * Names this installation to the backend, so a report that quotes the same id can be found in
     * the console.
     *
     * The id is generated by the application and kept in its settings; it identifies an install, not
     * a person, and is only ever sent once the user has consented.
     *
     * @param installationId The id this installation is known by.
     */
    fun identify(installationId: String)

    /**
     * Sends one line.
     *
     * Only called for lines the user's consent allows: see `TelemetryLogWriter`.
     *
     * @param level How loud the line is.
     * @param tag Who wrote it.
     * @param message The line itself.
     * @param throwable The failure that came with it, when there is one.
     */
    fun record(level: LogLevel, tag: String, message: String, throwable: Throwable?)

    /** Asks the backend to forget everything it holds about this installation. */
    fun forgetMe()
}
